UPDATE AccountBean
SET password="cs4010"
WHERE account_id="1";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="2";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="3";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="4";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="5";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="6";
UPDATE AccountBean
SET password="cs4010"
WHERE account_id="7";